# Generated by Django 3.1.7 on 2021-03-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
    ]
