# Generated by Django 3.1.7 on 2021-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_user_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual',
            field=models.BooleanField(default=True, help_text='If false,account automatically becomes a business account'),
        ),
    ]
