# Generated by Django 3.1.6 on 2021-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210302_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual',
            field=models.BooleanField(default=True, help_text='If false, account automatically becomes a business account'),
        ),
    ]
