# Generated by Django 3.1.6 on 2021-03-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210304_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual',
            field=models.BooleanField(default=False, help_text='Click to create an individual account'),
        ),
    ]
